config/routes.rb
CaLottoNumbers::Application.routes.draw do
  resources :ca_lotto_numbers

end

app/models/ca_lotto_number.rb
class CaLottoNumber < ActiveRecord::Base
  attr_accessible :bonusNumber, :number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ca_lotto_numbers_controller.rb
class CaLottoNumbersController < ApplicationController
  # GET /ca_lotto_numbers
  # GET /ca_lotto_numbers.json
  def index
    @ca_lotto_numbers = CaLottoNumber.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ca_lotto_numbers }
    end
  end

  # GET /ca_lotto_numbers/1
  # GET /ca_lotto_numbers/1.json
  def show
    @ca_lotto_number = CaLottoNumber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ca_lotto_number }
    end
  end

  # GET /ca_lotto_numbers/new
  # GET /ca_lotto_numbers/new.json
  def new
    @ca_lotto_number = CaLottoNumber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ca_lotto_number }
    end
  end

  # GET /ca_lotto_numbers/1/edit
  def edit
    @ca_lotto_number = CaLottoNumber.find(params[:id])
  end

  # POST /ca_lotto_numbers
  # POST /ca_lotto_numbers.json
  def create
    @ca_lotto_number = CaLottoNumber.new(params[:ca_lotto_number])

    respond_to do |format|
      if @ca_lotto_number.save
        format.html { redirect_to @ca_lotto_number, notice: 'Ca lotto number was successfully created.' }
        format.json { render json: @ca_lotto_number, status: :created, location: @ca_lotto_number }
      else
        format.html { render action: "new" }
        format.json { render json: @ca_lotto_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ca_lotto_numbers/1
  # PUT /ca_lotto_numbers/1.json
  def update
    @ca_lotto_number = CaLottoNumber.find(params[:id])

    respond_to do |format|
      if @ca_lotto_number.update_attributes(params[:ca_lotto_number])
        format.html { redirect_to @ca_lotto_number, notice: 'Ca lotto number was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ca_lotto_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ca_lotto_numbers/1
  # DELETE /ca_lotto_numbers/1.json
  def destroy
    @ca_lotto_number = CaLottoNumber.find(params[:id])
    @ca_lotto_number.destroy

    respond_to do |format|
      format.html { redirect_to ca_lotto_numbers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ca_lotto_numbers_helper.rb
module CaLottoNumbersHelper
end

app/views/ca_lotto_numbers/_form.html.erb
<%= form_for(@ca_lotto_number) do |f| %>
  <% if @ca_lotto_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ca_lotto_number.errors.count, "error") %> prohibited this ca_lotto_number from being saved:</h2>

      <ul>
      <% @ca_lotto_number.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :bonusNumber %><br />
    <%= f.text_field :bonusNumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ca_lotto_numbers/edit.html.erb
<h1>Editing ca_lotto_number</h1>

<%= render 'form' %>

<%= link_to 'Show', @ca_lotto_number %> |
<%= link_to 'Back', ca_lotto_numbers_path %>

app/views/ca_lotto_numbers/index.html.erb
<h1>Listing ca_lotto_numbers</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Bonusnumber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ca_lotto_numbers.each do |ca_lotto_number| %>
  <tr>
    <td><%= ca_lotto_number.number %></td>
    <td><%= ca_lotto_number.bonusNumber %></td>
    <td><%= link_to 'Show', ca_lotto_number %></td>
    <td><%= link_to 'Edit', edit_ca_lotto_number_path(ca_lotto_number) %></td>
    <td><%= link_to 'Destroy', ca_lotto_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ca lotto number', new_ca_lotto_number_path %>

app/views/ca_lotto_numbers/new.html.erb
<h1>New ca_lotto_number</h1>

<%= render 'form' %>

<%= link_to 'Back', ca_lotto_numbers_path %>

app/views/ca_lotto_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @ca_lotto_number.number %>
</p>

<p>
  <b>Bonusnumber:</b>
  <%= @ca_lotto_number.bonusNumber %>
</p>


<%= link_to 'Edit', edit_ca_lotto_number_path(@ca_lotto_number) %> |
<%= link_to 'Back', ca_lotto_numbers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CaLottoNumbers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>